const Data=[
    {
    id: 1,
    name : "Housing Property 1",
    description : "Lorem ipsum dolor sit amet consectetur adipifg elit. Architecto Lorem ipsum dolor sit amet consectetur adipifg elit. Architecto est, tenetur sequi debitis tempora eos mollitia assumenda soluta ut amet sequi debitis tempora eos mollitia assumenda soluta ut amet.",
    img: "https://images.unsplash.com/photo-1600585154526-990dced4db0d?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=387&q=80",
    price : "50,00,000",
    city : "Rajkot",
    state : "Gujarat",
    alt : "Loading...",
    sqft : "2400",
    category : "House",
    action : "Buy"
},
{
    id: 2,
    name : "Housing Property 2",
    description : "Lorem ipsum dolor sit amet consectetur adipifg elit. Architecto Lorem ipsum dolor sit amet consectetur adipifg elit. Architecto est, tenetur sequi debitis tempora eos mollitia assumenda soluta ut amet sequi debitis tempora eos mollitia assumenda soluta ut amet.",
    img: "https://images.unsplash.com/photo-1516156008625-3a9d6067fab5?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1170&q=80",
    price : "43,70,000",
    city : "Ahmedabad",
    state : "Gujarat",
    alt : "Loading...",
    sqft : "1200",
    category : "House",
    action : "Rent"
},
{
    id: 3,
    name : "Housing Property 3",
    description : "Lorem ipsum dolor sit amet consectetur adipifg elit. Architecto Lorem ipsum dolor sit amet consectetur adipifg elit. Architecto est, tenetur sequi debitis tempora eos mollitia assumenda soluta ut amet sequi debitis tempora eos mollitia assumenda soluta ut amet.",
    img: "https://images.unsplash.com/photo-1601622962666-d0b6d43a7ac7?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8MjN8fGxhbmQlMjBwbG90fGVufDB8fDB8fA%3D%3D&auto=format&fit=crop&w=500&q=60",
    price : "80,70,000",
    city : "Mumbai",
    state : "Maharashtra",
    alt : "Loading...",
    sqft : "800",
    category : "House",
    action : "Rent"
},
{
    id: 4,
    name : "Housing Property 4",
    description : "Lorem ipsum dolor sit amet consectetur adipifg elit. Architecto Lorem ipsum dolor sit amet consectetur adipifg elit. Architecto est, tenetur sequi debitis tempora eos mollitia assumenda soluta ut amet sequi debitis tempora eos mollitia assumenda soluta ut amet.",
    img: "https://images.unsplash.com/photo-1492889971304-ac16ab4a4a5a?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1yZWxhdGVkfDZ8fHxlbnwwfHx8fA%3D%3D&auto=format&fit=crop&w=500&q=60",
    price : "45,00,000",
    city : "New Delhi",
    state : "Delhi",
    alt : "Loading...",
    sqft : "3600",
    category : "House",
    action : "Rent"
},
{
    id: 5,
    name : "Housing Property 5",
    description : "Lorem ipsum dolor sit amet consectetur adipifg elit. Architecto Lorem ipsum dolor sit amet consectetur adipifg elit. Architecto est, tenetur sequi debitis tempora eos mollitia assumenda soluta ut amet sequi debitis tempora eos mollitia assumenda soluta ut amet.",
    img: "https://images.unsplash.com/photo-1610569244414-5e7453a447a8?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=774&q=80",
    price : "75,30,000",
    city : "Shimla",
    state : "Himachal Pradesh",
    alt : "Loading...",
    sqft : "1000",
    category : "House",
    action : "Buy"
},
{
    id: 6,
    name : "Housing Property 6",
    description : "Lorem ipsum dolor sit amet consectetur adipifg elit. Architecto Lorem ipsum dolor sit amet consectetur adipifg elit. Architecto est, tenetur sequi debitis tempora eos mollitia assumenda soluta ut amet sequi debitis tempora eos mollitia assumenda soluta ut amet.",
    img: "https://images.unsplash.com/photo-1489370321024-e0410ad08da4?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1yZWxhdGVkfDE0fHx8ZW58MHx8fHw%3D&auto=format&fit=crop&w=500&q=60",
    price : "30,90,000",
    city : "Kolkata",
    state : "West Bengal",
    alt : "Loading...",
    sqft : "900",
    category : "House",
    action : "Rent"
},
{
    id: 7,
    name : "Housing Property 7",
    description : "Lorem ipsum dolor sit amet consectetur adipifg elit. Architecto Lorem ipsum dolor sit amet consectetur adipifg elit. Architecto est, tenetur sequi debitis tempora eos mollitia assumenda soluta ut amet sequi debitis tempora eos mollitia assumenda soluta ut amet.",
    img: "https://images.unsplash.com/photo-1574362848149-11496d93a7c7?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1yZWxhdGVkfDE5fHx8ZW58MHx8fHw%3D&auto=format&fit=crop&w=500&q=60",
    price : "60,20,000",
    city : "Chennai",
    state : "Tamil Nadu",
    alt : "Loading...",
    sqft : "2900",
    category : "House",
    action : "Buy"
},
{
    id: 8,
    name : "Showroom Property 1",
    description : "Lorem ipsum dolor sit amet consectetur adipifg elit. Architecto Lorem ipsum dolor sit amet consectetur adipifg elit. Architecto est, tenetur sequi debitis tempora eos mollitia assumenda soluta ut amet sequi debitis tempora eos mollitia assumenda soluta ut amet.",
    img: "https://images.unsplash.com/photo-1562088972-6c6087002996?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8OHx8c2hvd3Jvb20lMjBwcm9wZXJ0eXxlbnwwfHwwfHw%3D&auto=format&fit=crop&w=500&q=60",
    price : "54,00,000",
    city : "Mumbai",
    state : "Maharashtra",
    alt : "Loading...",
    sqft : "1600",
    category : "Commercial",
    action : "Buy"

},
{
    id: 9,
    name : "Housing Property 8",
    description : "Lorem ipsum dolor sit amet consectetur adipifg elit. Architecto Lorem ipsum dolor sit amet consectetur adipifg elit. Architecto est, tenetur sequi debitis tempora eos mollitia assumenda soluta ut amet sequi debitis tempora eos mollitia assumenda soluta ut amet.",
    img: "https://images.unsplash.com/photo-1483097365279-e8acd3bf9f18?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8Mjd8fHNob3dyb29tJTIwcHJvcGVydHl8ZW58MHx8MHx8&auto=format&fit=crop&w=500&q=60",
    price : "63,00,000",
    city : "Indore",
    state : "Madhya Pradesh",
    alt : "Loading...",
    sqft : "1100",
    category : "House",
    action : "Buy"
},
{
    id: 10,
    name : "Showroom Property 2",
    description : "Lorem ipsum dolor sit amet consectetur adipifg elit. Architecto Lorem ipsum dolor sit amet consectetur adipifg elit. Architecto est, tenetur sequi debitis tempora eos mollitia assumenda soluta ut amet sequi debitis tempora eos mollitia assumenda soluta ut amet.",
    img: "https://images.unsplash.com/photo-1516274626895-055a99214f08?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8MXx8c2hvcHMlMjBlbXB0eXxlbnwwfHwwfHw%3D&auto=format&fit=crop&w=500&q=60",
    price : "46,48,000",
    city : "New Delhi",
    state : "Delhi",
    alt : "Loading...",
    sqft : "4000",
    category : "Commercial",
    action : "Buy"
},
{
    id: 11,
    name : "Showroom Property 3",
    description : "Lorem ipsum dolor sit amet consectetur adipifg elit. Architecto Lorem ipsum dolor sit amet consectetur adipifg elit. Architecto est, tenetur sequi debitis tempora eos mollitia assumenda soluta ut amet sequi debitis tempora eos mollitia assumenda soluta ut amet.",
    img: "https://images.unsplash.com/photo-1575729312527-1bdecaae271e?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8NXx8c2hvcHMlMjBlbXB0eXxlbnwwfHwwfHw%3D&auto=format&fit=crop&w=500&q=60",
    price : "42,65,000",
    city : "Kolkata",
    state : "West Bengal",
    alt : "Loading...",
    sqft : "700",
    category : "Commercial",
    action : "Rent"
},
{
    id: 12,
    name : "Office Property 1",
    description : "Lorem ipsum dolor sit amet consectetur adipifg elit. Architecto Lorem ipsum dolor sit amet consectetur adipifg elit. Architecto est, tenetur sequi debitis tempora eos mollitia assumenda soluta ut amet sequi debitis tempora eos mollitia assumenda soluta ut amet.",
    img: "https://images.unsplash.com/photo-1556761175-4b46a572b786?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8Nnx8b2ZmaWNlJTIwcHJvcGVydHl8ZW58MHx8MHx8&auto=format&fit=crop&w=500&q=60",
    price : "89,45,000",
    city : "Bangalore",
    state : "Karnatak",
    alt : "Loading...",
    sqft : "1900",
    category : "Commercial",
    action : "Buy"
},
{
    id: 13,
    name : "Office Property 2",
    description : "Lorem ipsum dolor sit amet consectetur adipifg elit. Architecto Lorem ipsum dolor sit amet consectetur adipifg elit. Architecto est, tenetur sequi debitis tempora eos mollitia assumenda soluta ut amet sequi debitis tempora eos mollitia assumenda soluta ut amet.",
    img: "https://images.unsplash.com/photo-1497366412874-3415097a27e7?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8MTR8fG9mZmljZSUyMHByb3BlcnR5fGVufDB8fDB8fA%3D%3D&auto=format&fit=crop&w=500&q=60",
    price : "50,70,000",
    city : "Ahmedabad",
    state : "Gujarat",
    alt : "Loading...",
    sqft : "2100",
    category : "Commercial",
    action : "Buy & Rent"},
{
    id: 14,
    name : "Office Property 3",
    description : "Lorem ipsum dolor sit amet consectetur adipifg elit. Architecto Lorem ipsum dolor sit amet consectetur adipifg elit. Architecto est, tenetur sequi debitis tempora eos mollitia assumenda soluta ut amet sequi debitis tempora eos mollitia assumenda soluta ut amet.",
    img: "https://images.unsplash.com/photo-1588148208486-a3b096a44537?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8MjB8fG9mZmljZSUyMHByb3BlcnR5fGVufDB8fDB8fA%3D%3D&auto=format&fit=crop&w=500&q=60",
    price : "87,00,000",
    city : "Chandigarh",
    state : "Punjab",
    alt : "Loading...",
    sqft : "1550",
    category : "Commercial",
    action : "Rent"
},
{
    id: 15,
    name : "Land Plot 1",
    description : "Lorem ipsum dolor sit amet consectetur adipifg elit. Architecto Lorem ipsum dolor sit amet consectetur adipifg elit. Architecto est, tenetur sequi debitis tempora eos mollitia assumenda soluta ut amet sequi debitis tempora eos mollitia assumenda soluta ut amet.",
    img: "https://images.unsplash.com/photo-1587745890135-20db8c79b027?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8Mnx8bGFuZCUyMHBsb3R8ZW58MHx8MHx8&auto=format&fit=crop&w=500&q=60",
    price : "52,10,000",
    city : "Lucknow",
    state : "Uttar Pradesh",
    alt : "Loading...",
    sqft : "2150",
    category : "Land",
    action : "Buy"
},
{
    id: 16,
    name : "Land Plot 2",
    description : "Lorem ipsum dolor sit amet consectetur adipifg elit. Architecto Lorem ipsum dolor sit amet consectetur adipifg elit. Architecto est, tenetur sequi debitis tempora eos mollitia assumenda soluta ut amet sequi debitis tempora eos mollitia assumenda soluta ut amet.",
    img: "https://images.unsplash.com/photo-1586859821520-523558cbebe8?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8N3x8bGFuZCUyMHBsb3R8ZW58MHx8MHx8&auto=format&fit=crop&w=500&q=60",
    price : "78,65,000",
    city : "Chennai",
    state : "Tamil Nadu",
    alt : "Loading...",
    sqft : "1150",
    category : "Land",
    action : "Buy & Rent"},
{
    id: 17,
    name : "Land Plot 3",
    description : "Lorem ipsum dolor sit amet consectetur adipifg elit. Architecto Lorem ipsum dolor sit amet consectetur adipifg elit. Architecto est, tenetur sequi debitis tempora eos mollitia assumenda soluta ut amet sequi debitis tempora eos mollitia assumenda soluta ut amet.",
    img: "https://images.unsplash.com/photo-1586859821397-c81e4971ca82?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8MTR8fGxhbmQlMjBwbG90fGVufDB8fDB8fA%3D%3D&auto=format&fit=crop&w=500&q=60",
    price : "71,50,000",
    city : "Rajkot",
    state : "Gujarat",
    alt : "Loading...",
    sqft : "3000",
    category : "Land",
    action : "Buy"
},
{
    id: 18,
    name : "Showroom Property 4",
    description : "Lorem ipsum dolor sit amet consectetur adipifg elit. Architecto Lorem ipsum dolor sit amet consectetur adipifg elit. Architecto est, tenetur sequi debitis tempora eos mollitia assumenda soluta ut amet sequi debitis tempora eos mollitia assumenda soluta ut amet.",
    img: "https://images.unsplash.com/photo-1584960051562-fd30e1093ac0?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8MTZ8fHNob3BzJTIwZW1wdHl8ZW58MHx8MHx8&auto=format&fit=crop&w=500&q=60",
    price : "70,00,000",
    city : "Pune",
    state : "Maharashtra",
    alt : "Loading...",
    sqft : "2800",
    category : "Commercial",
    action : "Buy & Rent"},
{
    id: 19,
    name : "Land Plot 4",
    description : "Lorem ipsum dolor  consectetur adipifg elit. Architecto Lorem ipsum dolor sit amet consectetur adipifg elit. Architecto est, tenetur sequi debitis tempora eos mollitia assumenda soluta ut amet sequi debitis tempora eos mollitia assumenda soluta ut amet.",
    img: "https://images.unsplash.com/photo-1635548758456-241032d7a8f2?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8NDZ8fGxhbmQlMjBwbG90fGVufDB8fDB8fA%3D%3D&auto=format&fit=crop&w=500&q=60",
    price : "59,60,000",
    city : "Shimla",
    state : "Himachal Pradesh",
    alt : "Loading...",
    sqft : "3100",
    category : "Land",
    action : "Buy"
},
{
    id: 20,
    name : "Office Property 4",
    description : "Lorem ipsum dolor sit amet consectetur adipifg elit. Architecto Lorem ipsum dolor sit amet consectetur adipifg elit. Architecto est, tenetur sequi debitis tempora eos mollitia assumenda soluta ut amet sequi debitis tempora eos mollitia assumenda soluta ut amet.",
    img: "https://images.unsplash.com/photo-1616436818581-24e51d77e473?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8NTJ8fG9mZmljZSUyMHByb3BlcnR5fGVufDB8fDB8fA%3D%3D&auto=format&fit=crop&w=500&q=60",
    price : "35,00,000",
    city : "Dispur",
    state : "Assam",
    alt : "Loading...",
    sqft : "3150",  
    category : "Commercial",
    action : "Buy & Rent"  
}
]

export default Data;

